#!/bin/bash
#
# Init file for ncm-cdispd daemon
#
# chkconfig: 345 30 80
# description: The Configuration Dispatch Daemon

. /etc/rc.d/init.d/functions

DISPATCH=/usr/sbin/ncm-cdispd
RETVAL=0
prog="ncm-cdispd"

start() {
    bash -c "echo -n 'Starting $prog:'"
    daemon "$DISPATCH" -D
    RETVAL=$?
    [ "$RETVAL" = 0 ] && touch /var/lock/quattor/ncm-cdispd
    echo
}

stop() {
    bash -c "echo -n 'Stopping $prog:'"
    killproc $DISPATCH -TERM
    RETVAL=$?
    [ "$RETVAL" = 0 ] && rm -f /var/lock/quattor/ncm-cdispd
    echo
}

reload() {
    bash -c "echo -n 'Reloading $prog:'"
    killproc $DISPATCH -HUP
    RETVAL=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $DISPATCH
        RETVAL=$?
        ;;
    reload)
        reload
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        RETVAL=1
esac

exit $RETVAL
